### ISSUE TITLE
Choosing between different  sources(H/W &S/W)

### ISSUE THREAD

**Issue by AhmadAbdelsalam** [ahmedtarek97/ASUMobiCarG66#1]
we searched for the difference between different types of microcontrollers and everyone gives their opinion

**Comment by AhmadAbdelsalam** [comment]
[AVR.docx](https://github.com/ahmedtarek97/ASUMobiCarG66/files/1745066/AVR.docx)

**Comment by AhmedGalal21** [comment]
[Control project.pdf](https://github.com/ahmedtarek97/ASUMobiCarG66/files/1745317/Control.project.pdf)

**Comment by AhmedAllien** [comment]
[Task.pdf](https://github.com/ahmedtarek97/ASUMobiCarG66/files/1745353/Task.pdf)

**Comment by AhmedElgamiel** [comment]
[Control Project.docx](https://github.com/ahmedtarek97/ASUMobiCarG66/files/1745616/Control.Project.docx)

**Comment by Ahmdnsr** [comment]
[Control project.docx](https://github.com/ahmedtarek97/ASUMobiCarG66/files/1745626/Control.project.docx)

**Comment by Ahmad-sayed** [comment]
[Arduino vs Avr.pdf](https://github.com/ahmedtarek97/ASUMobiCarG66/files/1745771/Arduino.vs.Avr.pdf)

**Comment by ahmdshrf** [comment]
[Arduino VS Atmega.pdf](https://github.com/ahmedtarek97/ASUMobiCarG66/files/1745781/Arduino.VS.Atmega.pdf)

**Comment by AHMED-3RFA** [comment]
[arduino.docx](https://github.com/ahmedtarek97/ASUMobiCarG66/files/1745797/arduino.docx)

**Comment by EL-SHREIF** [comment]
[task 1.docx](https://github.com/ahmedtarek97/ASUMobiCarG66/files/1747537/task.1.docx)

**Comment by ahmedtarek97** [comment]
[control.pdf](https://github.com/ahmedtarek97/ASUMobiCarG66/files/1748004/control.pdf)
