### ISSUE TITLE
phase 2 simplest track

### ISSUE THREAD

**Issue by AhmadAbdelsalam** [ahmedtarek97/ASUMobiCarG66#10]
we divided this phase into two main categories
1- simplest track
2-developments in our work (complex and and and)

for simplest track we divide ourselves into 5 teams
1-first team responsible for searching for another (sensors and motors) which can fulfill our target @Ahmdnsr @AhmedGalal21 @Ahmad-sayed @AhmedAllien 
2-second team @EL-SHREIF @AhmedElgamiel  working on AVR code for this phase
3-third team @AHMED-3RFA & @AhmadAbdelsalam  responsible for the code of INfrared sensors
4-fourth team: @ahmedtarek97  working on the application
5-fifth team: @ahmdshrf  working on enhancements of phase 1 code

6-some sources may be helpful 
https://www.youtube.com/watch?v=YKTGZuTeaU0
https://www.youtube.com/watch?v=F1-pWC4HmHg
http://mertarduinotutorial.blogspot.com.eg/2017/10/line-following-follower-robot-car-with.html
https://store.fut-electronics.com/collections/light-infrared-sound/products/infrared-object-detection-sensor
http://ram-e-shop.com/oscmax/catalog/product_info.php?products_id=3227
http://mertarduinotutorial.blogspot.com.eg/2016/12/arduino-project-tutorial-12-line.html

**Comment by Ahmdnsr** [comment]
![arduino-line-follower-robot-circuit](https://user-images.githubusercontent.com/36520429/38164383-f7bb66b4-3503-11e8-90b1-9e398f1bc901.jpg)
this is my design

**Comment by Ahmad-sayed** [comment]
[Task.docx](https://github.com/ahmedtarek97/ASUMobiCarG66/files/1872937/Task.docx)

**Comment by AhmedGalal21** [comment]
the sensor which i told you last night @AhmadAbdelsalam   Hardware Required :
[3way_line_tracker_sensor_tutorial (1).pdf](https://github.com/ahmedtarek97/ASUMobiCarG66/files/1874748/3way_line_tracker_sensor_tutorial.1.pdf)

**Comment by AhmedGalal21** [comment]
[line-finder-arduino.pdf](https://github.com/ahmedtarek97/ASUMobiCarG66/files/1874753/line-finder-arduino.pdf)

**Comment by AhmedGalal21** [comment]
https://store.fut-electronics.com/collections/light-infrared-sound/products/line-tracker-finder-sensor-vertical

**Comment by AhmedGalal21** [comment]
https://www.dfrobot.com/wiki/index.php/Line_Tracking_Sensor_for_Arduino_(SKU:SEN0017)

**Comment by AhmedGalal21** [comment]
https://www.dfrobot.com/wiki/index.php/Line_Tracking_Sensor_for_Arduino_V4_SKU:SEN0017
5-ch ITR20001/T infrared detector i think this one is very useful 
https://www.robotshop.com/en/infrared-line-tracking-sensor.html
