### ISSUE TITLE
Sheet 1 solution

### ISSUE THREAD

**Issue by AhmadAbdelsalam** [ahmedtarek97/ASUMobiCarG66#2]

**Comment by AhmadAbdelsalam** [comment]
[solution of sheet one.docx](https://github.com/ahmedtarek97/ASUMobiCarG66/files/1745202/solution.of.sheet.one.docx)
solution of sheet one using arduino

**Comment by AhmedGalal21** [comment]
[Solution of sheet 1.docx](https://github.com/ahmedtarek97/ASUMobiCarG66/files/1745423/Solution.of.sheet.1.docx)

**Comment by Ahmdnsr** [comment]
[Pb1,2.docx](https://github.com/ahmedtarek97/ASUMobiCarG66/files/1745641/Pb1.2.docx)

**Comment by AhmedElgamiel** [comment]
[Sheet1 soluion.docx](https://github.com/ahmedtarek97/ASUMobiCarG66/files/1745835/Sheet1.soluion.docx)

**Comment by EL-SHREIF** [comment]
[task 2.docx](https://github.com/ahmedtarek97/ASUMobiCarG66/files/1747767/task.2.docx)
