### ISSUE TITLE
sheet 2 problem 3 (with timer)

### ISSUE THREAD

**Issue by EL-SHREIF** [ahmedtarek97/ASUMobiCarG66#7]
i want the code of this problem with timer in arduino or avr and explanation of way of using timer or any videos to learn it

**Comment by Ahmad-sayed** [comment]
you can check my code in code side

**Comment by Ahmad-sayed** [comment]
http://www.instructables.com/id/Build-a-Simple-Binary-Counter-using-your-Arduino/

**Comment by EL-SHREIF** [comment]
AVR?
