### ISSUE TITLE
 Any information about linetracking ? 

### ISSUE THREAD

**Issue by ahmdshrf** [ahmedtarek97/ASUMobiCarG66#9]

**Comment by Ahmdnsr** [comment]
![arduino-line-follower-robot-circuit](https://user-images.githubusercontent.com/36520429/38152085-33937094-3466-11e8-99ea-3db3d6bccaaa.jpg)

**Comment by Ahmdnsr** [comment]
and iam going to upload the code now

**Comment by Ahmdnsr** [comment]
what about using ultra sonic sensor instead of IR , would it be more accurate   ? 
whats your opinion ?
